/**
 * Prielipp (265112)
 *
 * If there is a bad label generated by Data 
 */

public class BadLabel extends Exception
{
  public BadLabel(String label) 
  {
    super("Error! Label '" + label + "' is invalid");
  }
}


